# Generated by Django 4.0.6 on 2022-07-17 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_tag_alter_review_id_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f3d0ced-b832-479b-991b-1188ce40f1cb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
